# templates/base_template.py
"""
Base Template Classes for Legal Documents.
Provides the foundation for all legal document templates.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class DocumentSection:
    """Represents a section in a legal document."""
    title: str
    content: str
    section_number: Optional[str] = None
    subsections: List['DocumentSection'] = field(default_factory=list)
    is_required: bool = True
    
    def to_text(self, indent_level: int = 0) -> str:
        """Convert section to formatted text."""
        indent = "    " * indent_level
        lines = []
        
        if self.section_number:
            lines.append(f"{indent}{self.section_number}. {self.title}")
        else:
            lines.append(f"{indent}{self.title}")
        
        if self.content:
            lines.append(f"{indent}{self.content}")
        
        for subsection in self.subsections:
            lines.append(subsection.to_text(indent_level + 1))
        
        return "\n".join(lines)


class DocumentTemplate(ABC):
    """Abstract base class for all legal document templates."""
    
    # Template metadata
    template_name: str = "Base Template"
    template_description: str = "Base legal document template"
    template_category: str = "general"
    
    # Document structure
    required_fields: List[str] = []
    optional_fields: List[str] = []
    
    def __init__(self, data: Dict[str, Any] = None):
        """Initialize template with optional data."""
        self.data = data or {}
        self.sections: List[DocumentSection] = []
        self.generated_at = datetime.now()
    
    @abstractmethod
    def get_structure(self) -> List[Dict[str, Any]]:
        """Return the document structure definition."""
        pass
    
    @abstractmethod
    def generate(self) -> str:
        """Generate the complete document from the template."""
        pass
    
    def get_header(self) -> str:
        """Generate document header."""
        return f"""
{'=' * 70}
{self.template_name.upper()}
{'=' * 70}

Date: {self.generated_at.strftime('%B %d, %Y')}

"""
    
    def get_footer(self) -> str:
        """Generate document footer."""
        return f"""

{'=' * 70}
Generated by AI Legal Assistant
Date: {self.generated_at.strftime('%B %d, %Y at %H:%M:%S')}
{'=' * 70}

DISCLAIMER: This document is generated for informational purposes only.
Please consult a qualified legal professional before using this document
for any legal proceedings or official purposes.
"""
    
    def validate_data(self) -> Dict[str, List[str]]:
        """Validate that all required fields are present."""
        errors = []
        warnings = []
        
        for field in self.required_fields:
            if field not in self.data or not self.data[field]:
                errors.append(f"Required field '{field}' is missing")
        
        for field in self.optional_fields:
            if field not in self.data:
                warnings.append(f"Optional field '{field}' not provided")
        
        return {"errors": errors, "warnings": warnings}
    
    def format_currency(self, amount: float) -> str:
        """Format currency in Indian Rupees."""
        return f"₹{amount:,.2f} (Rupees {self._number_to_words(int(amount))} only)"
    
    def _number_to_words(self, num: int) -> str:
        """Convert number to words (Indian system)."""
        if num == 0:
            return "Zero"
        
        ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", 
                "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", 
                "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"]
        tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", 
                "Sixty", "Seventy", "Eighty", "Ninety"]
        
        def convert_chunk(n):
            if n < 20:
                return ones[n]
            elif n < 100:
                return tens[n // 10] + (" " + ones[n % 10] if n % 10 else "")
            else:
                return ones[n // 100] + " Hundred" + (" " + convert_chunk(n % 100) if n % 100 else "")
        
        if num < 1000:
            return convert_chunk(num)
        elif num < 100000:
            return convert_chunk(num // 1000) + " Thousand" + (" " + convert_chunk(num % 1000) if num % 1000 else "")
        elif num < 10000000:
            return convert_chunk(num // 100000) + " Lakh" + (" " + self._number_to_words(num % 100000) if num % 100000 else "")
        else:
            return convert_chunk(num // 10000000) + " Crore" + (" " + self._number_to_words(num % 10000000) if num % 10000000 else "")


class TemplateRegistry:
    """Registry for managing document templates."""
    
    _templates: Dict[str, type] = {}
    
    @classmethod
    def register(cls, template_type: str, template_class: type):
        """Register a template class."""
        cls._templates[template_type.lower()] = template_class
    
    @classmethod
    def get_template(cls, template_type: str, data: Dict[str, Any] = None) -> Optional[DocumentTemplate]:
        """Get a template instance by type."""
        template_class = cls._templates.get(template_type.lower())
        if template_class:
            return template_class(data)
        return None
    
    @classmethod
    def list_templates(cls) -> List[str]:
        """List all registered templates."""
        return list(cls._templates.keys())
    
    @classmethod
    def get_template_info(cls) -> List[Dict[str, str]]:
        """Get information about all registered templates."""
        info = []
        for name, template_class in cls._templates.items():
            info.append({
                "name": name,
                "display_name": template_class.template_name,
                "description": template_class.template_description,
                "category": template_class.template_category
            })
        return info
